---
abstract: 'search torrentz.eu with WWW:Search'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  WWW::Search::Test: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Search-Torrentz
no_index:
  directory:
    - t
    - inc
requires:
  WWW::Search: 0
  perl: 5.014000
version: 0.001
