---
abstract: 'search torrentz.eu with WWW::Search'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  Test::RequiresInternet: '0'
  WWW::Search::Test: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Search-Torrentz
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TreeBuilder: '0'
  URI::Escape: '0'
  WWW::Search: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=www-search-torrentz.git
version: '0.001003'
